### ISSUE TITLE
Wish:  `rust-e1000.config`

### ISSUE THREAD

**Issue by stappersg** [fujita/rust-e1000#1]
This issue is for helping to reproduce the _rust e1000 module_.

File `README.md` already says _use https://github.com/fujita/linux/tree/rust-e1000_
`README.md` should also say something like:

```text
cp rust-e1000.config  ~/git/linux/.config
```

With `rust-e1000.config` having content for a succesfull build of _rust-for-linux-tree_.

**Comment by stappersg** [comment]
Probably also document
```text
make oldconfig && make prepare
```

Additional note: I haven't yet a succesfull build.

**Comment by fujita** [comment]
I would recommend you to use the configs used in Rust-for-Linux CI:
https://github.com/Rust-for-Linux/linux/tree/rust/.github/workflows

You need to enable `CONFIG_PCI` and `CONFIG_INET` with these configs.
