### ISSUE TITLE
Rust compiler 'rustc' is too new.

### ISSUE THREAD

**Issue by stappersg** [fujita/rust-e1000#2]
Hi,

Here a curious newbie reporting this:
```text
$ make LLVM=1 rustavailable
***
*** Rust compiler 'rustc' is too new. This may or may not work.
***   Your version:     1.65.0
***   Expected version: 1.62.0
***
Rust is available!
$
```

That is with
```text
$ git branch --verbose | grep '^*'
* rust-e1000 263f16d67d52 rust: add dma and io mapping
$
```
in https://github.com/fujita/linux/tree/rust-e1000

I get a succesfull (but yet untested) build with `make CC=clang`.

And with `make LLVM=1` in the _Linux source directory_ I get:
```text
$ make LLVM=1
  SYNC    include/config/auto.conf.cmd
scripts/Kconfig.include:40: linker 'ld.lld' not found
make[2]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[1]: *** [Makefile:693: syncconfig] Error 2
make: *** [Makefile:795: include/config/auto.conf.cmd] Error 2

$ 
```

Purpose / idea of this report is triggering responses like
* _works for me_
* _seeing the same_
* _over here also, using ..... as workaround_

**Comment by fujita** [comment]
Before compiling rust-e1000, you need the specific versions of rustc, lld, etc to build kernel with Rust support. You can build rust-e1000 with these versions.
